baseline: Hello
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: Yup. Nice to meet you!
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Thanh Trong
baseurl: /
canonicalurl: true
